-- DMS Migration Database Schema for Oracle
-- Run this script to create the required tables

-- Create DMS_DOCUMENT table
CREATE TABLE DMS_DOCUMENT (
    ID NUMBER(10) PRIMARY KEY,
    FILE_NAME NVARCHAR2(500) NOT NULL,
    EXTENSION NVARCHAR2(500) NOT NULL,
    PATH NVARCHAR2(500) NOT NULL,
    SIZE NUMBER(19) NOT NULL,
    TYPE_ID NUMBER(10) NOT NULL,
    CURRENT_VERSION NUMBER(10) NOT NULL,
    CREATION_TIME TIMESTAMP(7) NOT NULL,
    CREATOR_USER_ID NUMBER(19) NULL,
    LAST_MODIFICATION_TIME TIMESTAMP(7) NULL,
    LAST_MODIFIER_USER_ID NUMBER(19) NULL,
    IS_DELETED NUMBER(1) NOT NULL,
    DELETER_USER_ID NUMBER(19) NULL,
    DELETION_TIME TIMESTAMP(7) NULL,
    TENANT_ID NUMBER(10) NULL
);

-- Create sequence for DMS_DOCUMENT
CREATE SEQUENCE DMS_DOCUMENT_SEQ START WITH 1 INCREMENT BY 1;

-- Create trigger for auto-increment
CREATE OR REPLACE TRIGGER DMS_DOCUMENT_TRG
BEFORE INSERT ON DMS_DOCUMENT
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT DMS_DOCUMENT_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

-- Create index on FILE_NAME
CREATE INDEX IDX_DMS_DOCUMENT_FILENAME ON DMS_DOCUMENT(FILE_NAME);

-- Create DMS_DOCUMENT_INDEX table
CREATE TABLE DMS_DOCUMENT_INDEX (
    ID NUMBER(10) PRIMARY KEY,
    DOCUMENT_ID NUMBER(10) NOT NULL,
    INDEX_KEY NVARCHAR2(100) NOT NULL,
    INDEX_VALUE NVARCHAR2(500) NOT NULL,
    CREATION_TIME TIMESTAMP(7) NOT NULL,
    CONSTRAINT FK_DOCINDEX_DOCUMENT FOREIGN KEY (DOCUMENT_ID) 
        REFERENCES DMS_DOCUMENT(ID) ON DELETE CASCADE
);

-- Create sequence for DMS_DOCUMENT_INDEX
CREATE SEQUENCE DMS_DOCUMENT_INDEX_SEQ START WITH 1 INCREMENT BY 1;

-- Create trigger for auto-increment
CREATE OR REPLACE TRIGGER DMS_DOCUMENT_INDEX_TRG
BEFORE INSERT ON DMS_DOCUMENT_INDEX
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT DMS_DOCUMENT_INDEX_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

-- Create composite index on DOCUMENT_ID and INDEX_KEY
CREATE INDEX IDX_DMS_DOCINDEX_DOCID_KEY ON DMS_DOCUMENT_INDEX(DOCUMENT_ID, INDEX_KEY);

-- Create DMS_DOCUMENT_VERSION table
CREATE TABLE DMS_DOCUMENT_VERSION (
    ID NUMBER(10) PRIMARY KEY,
    DOCUMENT_ID NUMBER(10) NOT NULL,
    VERSION_NUMBER NUMBER(10) NOT NULL,
    FILE_NAME NVARCHAR2(500) NOT NULL,
    PATH NVARCHAR2(500) NOT NULL,
    SIZE NUMBER(19) NOT NULL,
    CREATION_TIME TIMESTAMP(7) NOT NULL,
    CREATOR_USER_ID NUMBER(19) NULL,
    CONSTRAINT FK_DOCVERSION_DOCUMENT FOREIGN KEY (DOCUMENT_ID) 
        REFERENCES DMS_DOCUMENT(ID) ON DELETE CASCADE
);

-- Create sequence for DMS_DOCUMENT_VERSION
CREATE SEQUENCE DMS_DOCUMENT_VERSION_SEQ START WITH 1 INCREMENT BY 1;

-- Create trigger for auto-increment
CREATE OR REPLACE TRIGGER DMS_DOCUMENT_VERSION_TRG
BEFORE INSERT ON DMS_DOCUMENT_VERSION
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT DMS_DOCUMENT_VERSION_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

-- Verify tables created
SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME LIKE 'DMS_%';
